### ISSUE TITLE
How to rewind/undo swipe?

### ISSUE THREAD

**Issue by ElyDantas** [AsynctaskCoffee/TinderLikeCardStack#2]
How to rewind/undo swipe?

**Comment by AsynctaskCoffee** [comment]
Hello sorry for late reply. This project is part of one of my freelance projects. I will not update this repo soon. But I ve added your request to my todo list for later. Thanks.

**Comment by jenjosAndroid** [comment]
Is there any possibility for undo swipe?

**Comment by AsynctaskCoffee** [comment]
Nope, sorry. But any pr is welcome :)
