### ISSUE TITLE
Execution failed for task ':app:checkDebugAarMetadata'. > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.    > Could not find com.github.AsynctaskCoffee:tinderlikecardstack:1.0.

### ISSUE THREAD

**Issue by DongjingZhong** [AsynctaskCoffee/TinderLikeCardStack#3]
Hi my friend ,

I love your project .
I tried to install it in my project ,
 maven { url 'https://jitpack.io' }  ;
 implementation 'com.github.AsynctaskCoffee:tinderlikecardstack:1.0' ;

However ,appears the error as follow :
`Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.AsynctaskCoffee:tinderlikecardstack:1.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/AsynctaskCoffee/tinderlikecardstack/1.0/tinderlikecardstack-1.0.pom
       - https://repo.maven.apache.org/maven2/com/github/AsynctaskCoffee/tinderlikecardstack/1.0/tinderlikecardstack-1.0.pom
       - https://jcenter.bintray.com/com/github/AsynctaskCoffee/tinderlikecardstack/1.0/tinderlikecardstack-1.0.pom
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

`

As follow is my system ,
`android {
    compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "com.gearsrun.stackviewapplication"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

    }`

Could you please take a look what happen please ,thank you so much!

**Comment by AsynctaskCoffee** [comment]
allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}

	dependencies {
	        implementation 'com.github.AsynctaskCoffee:TinderLikeCardStack:1.0'
	}

Normally, your declarations are true but you may declare them on wrong places. implementation part should be in Gradle app - maven declaration should be in main Gradle. 

You can also define project with maven

	<dependency>
	    <groupId>com.github.AsynctaskCoffee</groupId>
	    <artifactId>TinderLikeCardStack</artifactId>
	    <version>1.0</version>
	</dependency>


       <repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>

Also please check you should disable offline Gradle build. You can also download project and import as module.

**Comment by DongjingZhong** [comment]
> ```
> allprojects {
> 	repositories {
> 		...
> 		maven { url 'https://jitpack.io' }
> 	}
> }
> 
> dependencies {
>         implementation 'com.github.AsynctaskCoffee:TinderLikeCardStack:1.0'
> }
> ```
> 
> Normally, your declarations are true but you may declare them on wrong places. implementation part should be in Gradle app - maven declaration should be in main Gradle.
> 
> You can also define project with maven
> 
> ```
> <dependency>
>     <groupId>com.github.AsynctaskCoffee</groupId>
>     <artifactId>TinderLikeCardStack</artifactId>
>     <version>1.0</version>
> </dependency>
> 
> 
>    <repositories>
> 	<repository>
> 	    <id>jitpack.io</id>
> 	    <url>https://jitpack.io</url>
> 	</repository>
> </repositories>
> ```
> 
> Also please check you should disable offline Gradle build. You can also download project and import as module.

Thank you so much bro ,I import it as a model ,and it solves the problem !

**Comment by AsynctaskCoffee** [comment]
No problem dude, enjoy 🍻
